### ISSUE TITLE
Won't count PDF

### ISSUE THREAD

**Issue by Adrast** [ezgranet/pdfwordcounter#1]
<img width="508" alt="skaermbillede 2018-10-24 14 46 05" src="https://user-images.githubusercontent.com/14887881/47431188-9be24480-d79b-11e8-8ef3-cd39239d01c7.png">
As seen on the picture, I get an error when trying to count a PDF

**Comment by ezgranet** [comment]
Interesting.  I can't seem to reproduce it myself, but it looks like it's calling on Homebrew rather than using the poppler included with the app.  Did you build from scratch, or did you use the .zip version online?

**Comment by ezgranet** [comment]
Or is the file in an odd PDF format?

**Comment by Adrast** [comment]
I used the .zip version. It's a PDF I made with LaTex at Overleaf.com

**Comment by ezgranet** [comment]
Interesting—I just tested it on my own LaTeX made documents.  Could you try downloading the entire repository and using the .app included? (I just did so and could not reproduce)

**Comment by ezgranet** [comment]
The error you're getting seems to be related to this: https://stackoverflow.com/questions/17703510/dyld-library-not-loaded-reason-image-not-loaded

**Comment by ezgranet** [comment]
Per StackExchange, try brew update && brew upgrade

**Comment by Adrast** [comment]
You are right, it worked! my bad :)

**Comment by waspinator** [comment]
just updating brew didn't work for me but `brew install poppler` did

**Comment by ezgranet** [comment]
@waspinator  I re-released it to try to fix this issue, which seems to popup periodically with updates to Brew and Poppler.  It's apparently a common issue when referencing libraries that are also separately installed in Homebrew.  There's a few discussions of the issue on StackOverflow, but none seems to have found an elegant solution.  See, for example: https://stackoverflow.com/questions/49457773/dyld-library-not-loaded-usr-local-lib-libmpfr-4-dylib
